# -*- coding: utf-8 -*-

ACTION_OBJECT_FINANCE_HISTORY = "object_finance_history"
ACTION_OBJECT_ACTIVITY_PRESENCE = "object_activity_presence"
ACTION_MY_OBJECT_PRESENCE = "my_object_presence"
ACTION_OBJECT_ACTIVITY_TIMELINE = "object_activity_timeline"
ACTION_FINANCE_TURNOVER = "finance_turnover"
ACTION_FINANCE_GROSS_PROFIT = "finance_gross_profit"
ACTION_FINANCE_OBJECTS_SUMMARY = "finance_objects_summary"

ACTION_EMPLOYEE_ABSENCES_TOTAL = "employee_absences_total"
ACTION_EMPLOYEE_ABSENCES_DISPUTED = "employee_absences_disputed"
ACTION_EMPLOYEE_ABSENCES_MONTH = "employee_absences_month"
ACTION_EMPLOYEE_ABSENCES_MONTH_DETAILS = "employee_absences_month_details"

ACTION_EMPLOYEE_TIME_TOTAL = "employee_time_total"
ACTION_EMPLOYEE_TIME_MONTH = "employee_time_month"
ACTION_EMPLOYEE_TIME_MONTH_OBJECT = "employee_time_month_object"
ACTION_EMPLOYEE_TIME_DAYS_MONTH = "employee_time_days_month"
ACTION_EMPLOYEE_TIME_DAYS_MONTH_OBJECT = "employee_time_days_month_object"
ACTION_EMPLOYEE_TIME_DAY_TIMELINE = "employee_time_day_timeline"
ACTION_EMPLOYEE_TIME_DAY_OBJECT_TIMELINE = "employee_time_day_object_timeline"
ACTION_EMPLOYEE_ATTENDANCE_MONTH_SUMMARY = "employee_attendance_month_summary"
ACTION_EMPLOYEE_ATTENDANCE_DAY_DETAILS = "employee_attendance_day_details"

ACTION_EMPLOYEE_CALENDAR_DAY_PERIOD = "employee_calendar_day_period"
ACTION_EMPLOYEE_CALENDAR_DAY_UPCOMING = "employee_calendar_day_upcoming"

ACTION_EMPLOYEE_FINANCE_MONTH_LIST = "employee_finance_month_list"
ACTION_EMPLOYEE_FINANCE_MONTH_TOTAL = "employee_finance_month_total"
ACTION_EMPLOYEE_FINANCE_TOTAL = "employee_finance_total"
ACTION_EMPLOYEE_FINANCE_CASH_PLAN = "employee_finance_cash_plan"
ACTION_PAYROLL_QUEUE = "payroll_queue"
ACTION_PAYROLL_HISTORY = "payroll_history"

ACTION_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_TOTAL = "dispatcher_withhold_accrual_year_total"
ACTION_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_PERCENT_AVG = "dispatcher_withhold_accrual_year_percent_avg"
ACTION_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_TOTAL = "dispatcher_withhold_accrual_month_total"
ACTION_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_PERCENT_AVG = "dispatcher_withhold_accrual_month_percent_avg"
ACTION_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL = "dispatcher_withhold_accrual_user_total"
ACTION_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL_ALL_FIRMS = "dispatcher_withhold_accrual_user_total_all_firms"
ACTION_DISPATCHER_SETTLEMENT_QUEUE = "dispatcher_settlement_queue"

ACTION_WORKER_MONTH_WORK = "worker_month_work"
ACTION_WORKER_DAY_WORK_ALL_FIRMS = "worker_day_work_all_firms"
ACTION_WORKER_MONTH_WORK_ALL_FIRMS = "worker_month_work_all_firms"
ACTION_WORKER_FINES_YEAR_TOTAL = "worker_fines_year_total"
ACTION_WORKER_FINES_MONTH_LIST = "worker_fines_month_list"
ACTION_WORKER_FINES_YEAR_LIST_EXCLUDING_MONTH = "worker_fines_year_list_excluding_month"
ACTION_WORKER_FINES_TOTALS_ALL_FIRMS = "worker_fines_totals_all_firms"
ACTION_WORKER_FINES_LIST_ALL_FIRMS = "worker_fines_list_all_firms"
ACTION_WORKER_ABSENCES_LIST_ALL_FIRMS = "worker_absences_list_all_firms"

ENDPOINT_OBJECT_FINANCE_HISTORY = "/firms/{firm_id}/analytics/object-finance-history"
ENDPOINT_OBJECT_ACTIVITY_PRESENCE = "/firms/{firm_id}/analytics/object-activity-presence"
ENDPOINT_MY_OBJECT_PRESENCE = "/firms/{firm_id}/analytics/my-object-presence"
ENDPOINT_OBJECT_ACTIVITY_TIMELINE = "/firms/{firm_id}/analytics/object-activity-timeline"
ENDPOINT_FINANCE_TURNOVER = "/firms/{firm_id}/analytics/finance-turnover"
ENDPOINT_FINANCE_GROSS_PROFIT = "/firms/{firm_id}/analytics/finance-gross-profit"
ENDPOINT_FINANCE_OBJECTS_SUMMARY = "/firms/{firm_id}/analytics/finance-objects-summary"

ENDPOINT_EMPLOYEE_ABSENCES_TOTAL = "/firms/{firm_id}/analytics/employee/absences/total"
ENDPOINT_EMPLOYEE_ABSENCES_DISPUTED = "/firms/{firm_id}/analytics/employee/absences/disputed"
ENDPOINT_EMPLOYEE_ABSENCES_MONTH = "/firms/{firm_id}/analytics/employee/absences/month"
ENDPOINT_EMPLOYEE_ABSENCES_MONTH_DETAILS = "/firms/{firm_id}/analytics/employee/absences/month-details"

ENDPOINT_EMPLOYEE_TIME_TOTAL = "/firms/{firm_id}/analytics/employee/time/total"
ENDPOINT_EMPLOYEE_TIME_MONTH = "/firms/{firm_id}/analytics/employee/time/month"
ENDPOINT_EMPLOYEE_TIME_MONTH_OBJECT = "/firms/{firm_id}/analytics/employee/time/month-object"
ENDPOINT_EMPLOYEE_TIME_DAYS_MONTH = "/firms/{firm_id}/analytics/employee/time/days-month"
ENDPOINT_EMPLOYEE_TIME_DAYS_MONTH_OBJECT = "/firms/{firm_id}/analytics/employee/time/days-month-object"
ENDPOINT_EMPLOYEE_TIME_DAY_TIMELINE = "/firms/{firm_id}/analytics/employee/time/day-timeline"
ENDPOINT_EMPLOYEE_TIME_DAY_OBJECT_TIMELINE = "/firms/{firm_id}/analytics/employee/time/day-object-timeline"
ENDPOINT_EMPLOYEE_ATTENDANCE_MONTH_SUMMARY = "/firms/{firm_id}/analytics/employee/attendance/month-summary"
ENDPOINT_EMPLOYEE_ATTENDANCE_DAY_DETAILS = "/firms/{firm_id}/analytics/employee/attendance/day-details"

ENDPOINT_EMPLOYEE_CALENDAR_DAY_PERIOD = "/firms/{firm_id}/analytics/employee/calendar/day-period"
ENDPOINT_EMPLOYEE_CALENDAR_DAY_UPCOMING = "/firms/{firm_id}/analytics/employee/calendar/day-upcoming"

ENDPOINT_EMPLOYEE_FINANCE_MONTH_LIST = "/firms/{firm_id}/analytics/employee/finance/month-list"
ENDPOINT_EMPLOYEE_FINANCE_MONTH_TOTAL = "/firms/{firm_id}/analytics/employee/finance/month-total"
ENDPOINT_EMPLOYEE_FINANCE_TOTAL = "/firms/{firm_id}/analytics/employee/finance/total"
ENDPOINT_EMPLOYEE_FINANCE_CASH_PLAN = "/firms/{firm_id}/analytics/employee/finance/cash-plan"
ENDPOINT_PAYROLL_QUEUE = "/firms/{firm_id}/analytics/payroll/queue"
ENDPOINT_PAYROLL_HISTORY = "/firms/{firm_id}/analytics/payroll/history"

ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_TOTAL = "/firms/{firm_id}/analytics/dispatcher-withhold-accrual-year-total"
ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_PERCENT_AVG = "/firms/{firm_id}/analytics/dispatcher-withhold-accrual-year-percent-avg"
ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_TOTAL = "/firms/{firm_id}/analytics/dispatcher-withhold-accrual-month-total"
ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_PERCENT_AVG = "/firms/{firm_id}/analytics/dispatcher-withhold-accrual-month-percent-avg"
ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL = "/firms/{firm_id}/analytics/dispatcher-withhold-accrual-user-total"
ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL_ALL_FIRMS = "/firms/{firm_id}/analytics/dispatcher-withhold-accrual-user-total-all-firms"
ENDPOINT_DISPATCHER_SETTLEMENT_QUEUE = "/firms/{firm_id}/analytics/dispatcher-settlement/queue"

ENDPOINT_WORKER_MONTH_WORK = "/firms/{firm_id}/analytics/worker-month-work"
ENDPOINT_WORKER_DAY_WORK_ALL_FIRMS = "/firms/{firm_id}/analytics/worker-day-work-all-firms"
ENDPOINT_WORKER_MONTH_WORK_ALL_FIRMS = "/firms/{firm_id}/analytics/worker-month-work-all-firms"
ENDPOINT_WORKER_FINES_YEAR_TOTAL = "/firms/{firm_id}/analytics/worker-fines-year-total"
ENDPOINT_WORKER_FINES_MONTH_LIST = "/firms/{firm_id}/analytics/worker-fines-month-list"
ENDPOINT_WORKER_FINES_YEAR_LIST_EXCLUDING_MONTH = "/firms/{firm_id}/analytics/worker-fines-year-list-excluding-month"
ENDPOINT_WORKER_FINES_TOTALS_ALL_FIRMS = "/firms/{firm_id}/analytics/worker-fines-totals-all-firms"
ENDPOINT_WORKER_FINES_LIST_ALL_FIRMS = "/firms/{firm_id}/analytics/worker-fines-list-all-firms"
ENDPOINT_WORKER_ABSENCES_LIST_ALL_FIRMS = "/firms/{firm_id}/analytics/worker-absences-list-all-firms"


def endpoint_for_action(action: str) -> str:
    mapping = {
        ACTION_OBJECT_FINANCE_HISTORY: ENDPOINT_OBJECT_FINANCE_HISTORY,
        ACTION_OBJECT_ACTIVITY_PRESENCE: ENDPOINT_OBJECT_ACTIVITY_PRESENCE,
        ACTION_MY_OBJECT_PRESENCE: ENDPOINT_MY_OBJECT_PRESENCE,
        ACTION_OBJECT_ACTIVITY_TIMELINE: ENDPOINT_OBJECT_ACTIVITY_TIMELINE,
        ACTION_FINANCE_TURNOVER: ENDPOINT_FINANCE_TURNOVER,
        ACTION_FINANCE_GROSS_PROFIT: ENDPOINT_FINANCE_GROSS_PROFIT,
        ACTION_FINANCE_OBJECTS_SUMMARY: ENDPOINT_FINANCE_OBJECTS_SUMMARY,
        ACTION_EMPLOYEE_ABSENCES_TOTAL: ENDPOINT_EMPLOYEE_ABSENCES_TOTAL,
        ACTION_EMPLOYEE_ABSENCES_DISPUTED: ENDPOINT_EMPLOYEE_ABSENCES_DISPUTED,
        ACTION_EMPLOYEE_ABSENCES_MONTH: ENDPOINT_EMPLOYEE_ABSENCES_MONTH,
        ACTION_EMPLOYEE_ABSENCES_MONTH_DETAILS: ENDPOINT_EMPLOYEE_ABSENCES_MONTH_DETAILS,
        ACTION_EMPLOYEE_TIME_TOTAL: ENDPOINT_EMPLOYEE_TIME_TOTAL,
        ACTION_EMPLOYEE_TIME_MONTH: ENDPOINT_EMPLOYEE_TIME_MONTH,
        ACTION_EMPLOYEE_TIME_MONTH_OBJECT: ENDPOINT_EMPLOYEE_TIME_MONTH_OBJECT,
        ACTION_EMPLOYEE_TIME_DAYS_MONTH: ENDPOINT_EMPLOYEE_TIME_DAYS_MONTH,
        ACTION_EMPLOYEE_TIME_DAYS_MONTH_OBJECT: ENDPOINT_EMPLOYEE_TIME_DAYS_MONTH_OBJECT,
        ACTION_EMPLOYEE_TIME_DAY_TIMELINE: ENDPOINT_EMPLOYEE_TIME_DAY_TIMELINE,
        ACTION_EMPLOYEE_TIME_DAY_OBJECT_TIMELINE: ENDPOINT_EMPLOYEE_TIME_DAY_OBJECT_TIMELINE,
        ACTION_EMPLOYEE_ATTENDANCE_MONTH_SUMMARY: ENDPOINT_EMPLOYEE_ATTENDANCE_MONTH_SUMMARY,
        ACTION_EMPLOYEE_ATTENDANCE_DAY_DETAILS: ENDPOINT_EMPLOYEE_ATTENDANCE_DAY_DETAILS,
        ACTION_EMPLOYEE_CALENDAR_DAY_PERIOD: ENDPOINT_EMPLOYEE_CALENDAR_DAY_PERIOD,
        ACTION_EMPLOYEE_CALENDAR_DAY_UPCOMING: ENDPOINT_EMPLOYEE_CALENDAR_DAY_UPCOMING,
        ACTION_EMPLOYEE_FINANCE_MONTH_LIST: ENDPOINT_EMPLOYEE_FINANCE_MONTH_LIST,
        ACTION_EMPLOYEE_FINANCE_MONTH_TOTAL: ENDPOINT_EMPLOYEE_FINANCE_MONTH_TOTAL,
        ACTION_EMPLOYEE_FINANCE_TOTAL: ENDPOINT_EMPLOYEE_FINANCE_TOTAL,
        ACTION_EMPLOYEE_FINANCE_CASH_PLAN: ENDPOINT_EMPLOYEE_FINANCE_CASH_PLAN,
        ACTION_PAYROLL_QUEUE: ENDPOINT_PAYROLL_QUEUE,
        ACTION_PAYROLL_HISTORY: ENDPOINT_PAYROLL_HISTORY,
        ACTION_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_TOTAL: ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_TOTAL,
        ACTION_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_PERCENT_AVG: ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_YEAR_PERCENT_AVG,
        ACTION_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_TOTAL: ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_TOTAL,
        ACTION_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_PERCENT_AVG: ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_MONTH_PERCENT_AVG,
        ACTION_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL: ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL,
        ACTION_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL_ALL_FIRMS: ENDPOINT_DISPATCHER_WITHHOLD_ACCRUAL_USER_TOTAL_ALL_FIRMS,
        ACTION_DISPATCHER_SETTLEMENT_QUEUE: ENDPOINT_DISPATCHER_SETTLEMENT_QUEUE,
        ACTION_WORKER_MONTH_WORK: ENDPOINT_WORKER_MONTH_WORK,
        ACTION_WORKER_DAY_WORK_ALL_FIRMS: ENDPOINT_WORKER_DAY_WORK_ALL_FIRMS,
        ACTION_WORKER_MONTH_WORK_ALL_FIRMS: ENDPOINT_WORKER_MONTH_WORK_ALL_FIRMS,
        ACTION_WORKER_FINES_YEAR_TOTAL: ENDPOINT_WORKER_FINES_YEAR_TOTAL,
        ACTION_WORKER_FINES_MONTH_LIST: ENDPOINT_WORKER_FINES_MONTH_LIST,
        ACTION_WORKER_FINES_YEAR_LIST_EXCLUDING_MONTH: ENDPOINT_WORKER_FINES_YEAR_LIST_EXCLUDING_MONTH,
        ACTION_WORKER_FINES_TOTALS_ALL_FIRMS: ENDPOINT_WORKER_FINES_TOTALS_ALL_FIRMS,
        ACTION_WORKER_FINES_LIST_ALL_FIRMS: ENDPOINT_WORKER_FINES_LIST_ALL_FIRMS,
        ACTION_WORKER_ABSENCES_LIST_ALL_FIRMS: ENDPOINT_WORKER_ABSENCES_LIST_ALL_FIRMS,
    }
    return mapping.get(action, "")


EVENT_TYPE_ACCRUAL = "ACCRUAL"
EVENT_TYPE_CASH = "CASH"
EVENT_TYPE_WITHHELD_SHIFT = "WITHHELD_SHIFT"
EVENT_TYPE_WITHHOLD_ACCRUAL = "WITHHOLD_ACCRUAL"
EVENT_TYPE_OBJ_COSTS = "OBJ_COSTS"
EVENT_TYPE_EMP_COSTS = "EMP_COSTS"
EVENT_TYPE_FINE = "FINE"
EVENT_TYPE_REWARD = "REWARD"
EVENT_TYPE_SHIFT_END = "SHIFT_END"
EVENT_TYPE_DEAL_COMPLETE = "DEAL_COMPLETE"
EVENT_TYPE_OBJ_ENTER = "obj_enter"
EVENT_TYPE_OBJ_LEAVE = "obj_leave"
EVENT_TYPE_SHIFT_ASSIGN = "SHIFT_ASSIGN"
EVENT_TYPE_DEAL_ASSIGN = "DEAL_ASSIGN"
EVENT_TYPE_EMP_OBJ_CHANGE = "EMP_OBJ_CHANGE"
EVENT_TYPE_OBJ_ATTACH = "OBJ_ATTACH"
EVENT_TYPE_OBJ_DETACH = "OBJ_DETACH"
EVENT_TYPE_ABSENCE = "absence"
EVENT_TYPE_SHIFT_START = "SHIFT_START"
EVENT_TYPE_SHIFT_REFUSE = "SHIFT_REFUSE"
EVENT_TYPE_SHIFT_CANCEL = "SHIFT_CANCEL"
EVENT_TYPE_DEAL_REFUSE = "DEAL_REFUSE"
EVENT_TYPE_DEAL_CANCEL = "DEAL_CANCEL"
EVENT_TYPE_SHIFT_FORCE_END = "SHIFT_FORCE_END"
EVENT_TYPE_ACCRUAL_DEFERRED = "ACCRUAL_DEFERRED"
EVENT_TYPE_DISPATCHER_SETTLEMENT = "DISPATCHER_SETTLEMENT"
